services:
  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: docker.io/library/mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s #Give DB time to initialize

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      - upload_limit=${PMA_UPLOAD_LIMIT}
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:

  # http://localhost:8081 
  # http://localhost:8080  